spring:
  application:
    name: car-service

server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

endpoint:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false